### PR TITLE
adds draft french translation

### PR DESCRIPTION
**Pull request by blinard-BIOINFO**
@asiekierka 

This PR adds a french translation.
Note that french is quite verbose compared to english... many sentences may not fit anymore on the small WS screen.

I also discarded the | character present in some sentences. I suppose they are line returns or page shifts ? (this is not explained in the readme)

With some help on the compilation, I'm happy to compile the ROM myself then test and adapt the text to fit better the screen limitations.

### CODE REVIEW

**Comment by asiekierka** [comment]
Unfortunately, we have, like, 27 characters of text *at maximum* available with the current 8x8 glyph text engine. Rewriting the code to support variable text width would be possible, but is not high priority.

**Comment by blinard-BIOINFO** [comment]
ok, I will do a second pass to try to fit in this limit.

**Comment by asiekierka** [comment]
That is correct; I've updated the README to match. I apologize for not responding earlier.

**Comment by blinard-BIOINFO** [comment]
@asiekierka I tried to fit everything things in 27 symbols per line as requested. Some lines fell a bit like smartphone text message style, but french is too verbose, I think I cannot do better...

**Comment by asiekierka** [comment]
I'm aware. I have written a proportional font renderer for a different project, but I haven't had time (or interest) in backporting it to CartFriend yet - it would require a medium-sized rework of how the UI code works.

**Pull request merged**
